#!/bin/bash

cd ..
find ../modules/kgeorgiy.implementor/info/kgeorgiy/java/advanced/implementor/ -name "*.java" > sources.txt
javac -d . @sources.txt &&
javac -d . ../modules/gunkin.implementor/ru/ifmo/rain/gunkin/implementor/*.java &&
java -cp . -p . -m info.kgeorgiy.java.advanced.implementor jar-advanced \
                   ru.ifmo.rain.gunkin.implementor.Implementor "$1"

rm sources.txt
